### ISSUE TITLE
Error when deploying image in cosigned enforced namespace

### ISSUE THREAD

**Issue by trondat** [sigstore/helm-charts#200] opened 2022-06-08 07:46 UTC
Hi,

When trying to run an image in a  namespace that is "cosigned enabled" , the webhook throws an error : 
```
Error from server (BadRequest): admission webhook "cosigned.sigstore.dev" denied the request: validation failed: invalid value: signed-image:master must be an image digest: spec.containers[0].image
```
The image is signed with cosign and verified with cosign using the same public key that is used for cosigned on K0s.

The same also applies when trying to deploy an unsigned image.

Any suggestion on what is wrong?

**Comment by hectorj2f** [comment] 2022-06-09 21:26
@trondat  The policy-controller webhook now requires digest references to validate references since the tag can move. So it is an expected behavior.

**Comment by bheisig** [comment] 2022-06-30 14:57
IMHO this (new?) behavior is too strict when you just start signing and verifying container images. Is it possible to make this optional? In my use care I don't care about image digests but care about image tags. All my images are signed by me. I "only" want to make sure every single container image from my private registry is built by me.

**Comment by hectorj2f** [comment] 2022-07-01 12:27
The decision comes to enforce the security of the verification.

**Comment by sabre1041** [comment] 2023-02-14 04:13
Closing issue has this is related to the policy-controller (then known as cosigned) and is not related to the chart itself

**Closed by sabre1041** 2023-02-14 04:13 UTC
Labels: bug
